import crypto from "crypto";
import * as jose from "jose";
import { generateSecureRandomString } from '@stackframe/stack-shared/dist/utils/crypto';

function generatePassword(length = 16) {
    const upperCase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowerCase = 'abcdefghijklmnopqrstuvwxyz';
    const numbers = '0123456789';
    const specialChars = '!%^_+-=';

    const allCharacters = upperCase + lowerCase + numbers + specialChars;
    const allLength = allCharacters.length;
    const passwordArray = [];

    // Ensure at least one character from each type
    passwordArray.push(upperCase[crypto.randomInt(upperCase.length)]);
    passwordArray.push(lowerCase[crypto.randomInt(lowerCase.length)]);
    passwordArray.push(numbers[crypto.randomInt(numbers.length)]);
    passwordArray.push(specialChars[crypto.randomInt(specialChars.length)]);

    // Fill the rest of the password with random characters
    for (let i = 4; i < length; i++) {
        passwordArray.push(allCharacters[crypto.randomInt(allLength)]);
    }

    // Shuffle to avoid predictable patterns
    for (let i = passwordArray.length - 1; i > 0; i--) {
        const j = crypto.randomInt(i + 1);
        [passwordArray[i], passwordArray[j]] = [passwordArray[j], passwordArray[i]];
    }

    return passwordArray.join('');
}

console.log("################# generated by generateKeys.ts #################")
console.log("# .env.dashbord")
console.log(`NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=pck_${generateSecureRandomString()}`)
console.log(`STACK_SECRET_SERVER_KEY=ssk_${generateSecureRandomString()}`)
console.log(`STACK_SUPER_SECRET_ADMIN_KEY=sak_${generateSecureRandomString()}`)
console.log()
console.log(`# .env.backend for backend server and webhooks`)
console.log(`STACK_SERVER_SECRET=${jose.base64url.encode(crypto.randomBytes(32))}`);
console.log(`STACK_SVIX_API_KEY=${jose.base64url.encode(crypto.randomBytes(64))}`)
console.log()
console.log(`# .env`)
console.log(`POSTGRES_STACKFRAME_PASSWORD=${generatePassword(20)}`);
console.log(`POSTGRES_SVIX_PASSWORD=${generatePassword(20)}`);
console.log("#----------------------------------------------------------------")